Patient.create(name: "AB", gender_id: 2, birthday: "2000-01-01", text: "テスト患者01")
Patient.create(name: "CD", gender_id: 3, birthday: "1990-01-01", text: "テスト患者02")
Patient.create(name: "EF", gender_id: 2, birthday: "1980-01-01", text: "テスト患者03")
Patient.create(name: "GH", gender_id: 2, birthday: "1970-01-01", text: "テスト患者04")

Plan.create(
  name: "PTX80＋Bev10 q4w",
  period: 28,
  emetic_id: 4,
  nk1: "不要",
  dex: "必要",
  h1blocker: "必要",
  h2blocker: "必要",
  other_medicine: "なし",
  text: "アルコール耐性を確認",
  medicine_name1: "パクリタキセル",
  medicine_name2: "ベバシズマブ",
  medicine_name3: "",
  medicine_name4: "",
  medicine_name5: "",
  medicine_name6: "",
  medicine_name7: "",
  medicine_name8: "",
  abbreviation1: "PTX",
  abbreviation2: "Bev",
  abbreviation3: "",
  abbreviation4: "",
  abbreviation5: "",
  abbreviation6: "",
  abbreviation7: "",
  abbreviation8: "",
  dose1: 80,
  dose2: 10,
  dose3: "",
  dose4: "",
  dose5: "",
  dose6: "",
  dose7: "",
  dose8: "",
  unit1_id: 2,
  unit2_id: 3,
  unit3_id: 1,
  unit4_id: 1,
  unit5_id: 1,
  unit6_id: 1,
  unit7_id: 1,
  unit8_id: 1,
  schedule1: "day1,8,15",
  schedule2: "day1,15",
  schedule3: "",
  schedule4: "",
  schedule5: "",
  schedule6: "",
  schedule7: "",
  schedule8: ""
)
Disease.create(cancer_id: 6, other_id: 2, purpose_id: 4, plan_id: 1)
Disease.create(cancer_id: 6, other_id: 3, purpose_id: 4, plan_id: 1)